### ISSUE TITLE
Better handling of author information

### ISSUE THREAD

**Issue by trans** [nilproductions/hugo-incorporated#25]
The author parameters seem to be all over the place, I have found `authorname`, `author_name` and `author.name`. I assume at least one of those is a bug, if not two.

Suggestion: Ideally we could add a list of authors in the main config, e.g.

    authors:
      - handle: tommy
        name: Tommy Boy
        twitter: tommyboy
        email: tommyboy@mail.com
      - handle: bek
        name: Becky Girl
        twitter: beckygirl
        email: beckygirl@mail.com

Then in posts simply putting the matching handle under the `author` param, or personally I'd prefer `by` param, all the rest of the author's information is picked up from the  main config.

**Comment by trans** [comment]
I figured out how to do this. But slightly different, using:

```
authors:
  tommy:
    name: Tommy Boy
    twitter: tommyboy
    email: tommyboy@mail.com
  bek:
    name: Becky Girl
    twitter: beckygirl
    email: beckygirl@mail.com
```

I can't submit a pull request.

Also, I think this is just generally the best way to go, and Hugo could use a standard approach to handling authors info, so I am going to propose that to them.
